// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function G_获取游戏名称(arg1:string):Promise<{[key: string]: string}>;

export function Greet(arg1:string):Promise<string>;
